config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  get "instance_table/:state" => 'instance_list#table'
  post "start_instance/:instance_id" => 'instance#start', as: :instance_start

end

app/models/activity_log.rb
class ActivityLog < ActiveRecord::Base
  belongs_to :user
end

app/models/aws_credentials.rb
class AwsCredentials

	def self.credentials
		if ENV.has_key?( 'AWS_SECURITY_TOKEN' )    # localhost
			puts "localhost"
			# get values from env.  requires me to have set them in advance
			# this shell script will do it for you:
			# https://drive.google.com/open?id=0B9zvaVUfUa8mRXE2TjdRTzc4UWM
			creds = Aws::Credentials.new( ENV['AWS_ACCESS_KEY_ID'], ENV['AWS_SECRET_ACCESS_KEY'], ENV['AWS_SECURITY_TOKEN'] )
		else
			puts "assume role"
			sts = Aws::STS::Client.new
			session = sts.assume_role( role_arn: ENV['ROLE_ARN'], role_session_name: ENV['ROLE_SESSION_NAME'] )
			creds = Aws::Credentials.new( session.credentials.access_key_id, session.credentials.secret_access_key, session.credentials.session_token )
		end		
	end

end

app/models/ec2/instance.rb
class Ec2::Instance

	attr_reader :raw

	def self.required_tags
		['Billing', 'FQDN', 'Contact', 'Service']
	end

	def self.states
		["stopped", "running", "terminated"]
	end

	def initialize( instance )
		@raw = instance
	end

	def id
		@raw[:instance_id]
	end

	def name
		tag_value("Name")
	end

	def tag_value( key )
		key = key.to_s
		val = @raw[:tags].select { |n|  n.key == key }[0].value
		if val
			val = val.gsub /^"/, ''
			val = val.gsub /"$/, ''
			val.strip
		end
	rescue 
		""
	end

end

app/models/ec2/service.rb
class Ec2::Service

	def initialize
		@@ec2 = ec2
	end

	def ec2
		creds = AwsCredentials.credentials
		Aws::EC2::Client.new( credentials: creds )
	end

	def instances( state )
		state = state.to_s
		@instances = []
		i = @@ec2.describe_instances( filters: [ { name: "instance-state-name", values: [state] } ] )
		i[:reservations].each do |reservation|
			reservation[:instances].each do |instance|
				@instances << Ec2::Instance.new(instance)
			end
		end
		@instances

	end


	def start_instance( instance_id ) 
		@@ec2.start_instances( instance_ids: [instance_id], additional_info: "", dry_run: false )
	end


end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate

  def authenticate
  	
  	if ( !request.session.has_key?("cas") )
  		puts "rendering 401"
  		render status: 401, text: ""
	  end
  end


  def current_user
    username = session['cas']['user']
    @current_user ||= User.find_by_username( username ) if username
    if @current_user == nil && username.length
      @current_user = User.create( username: username )
    end
    @current_user
  end

  helper_method :current_user 

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	def index
		
	end

end

app/controllers/instance_controller.rb
class InstanceController < ApplicationController

	def start
		instance_id = params[:instance_id]
		Ec2::Service.new.start_instance(instance_id)
		ActivityLog.create( user: current_user, action: "start", detail: "", resource_id: instance_id )
		render status: 200, json: {}
	end

end

app/controllers/instance_list_controller.rb
class InstanceListController < ApplicationController

	def table
		@instance_list = ec2_service.instances( params[:state] )
		render layout:false
	end

	def ec2_service
		@ec2 ||= Ec2::Service.new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.haml
%div#instance_list
	=image_tag "spinner.gif"

app/views/instance_list/table.html.haml
%table#instance_list.table.table-striped.table-hover.table-bordered.tablesorter
	%thead
		%tr
			%th{data: {priority: 'critical'}} Name
			%th{data: {priority: 'critical'}} Instance ID
			- Ec2::Instance.required_tags.each do |tag|
				%th{data: {priority: '5'}}= tag
			%th.filter-false{data: {priority: 'critical'}} Controls
	%tbody
		- @instance_list.each do |instance|
			%tr.instance_row
				%td.instance_name= instance.name
				%td.instance_id= instance.id
				- Ec2::Instance.required_tags.each do |tag|
					%td= instance.tag_value( tag )
				%td.controls= button_to "Wake Up", instance_start_path( instance_id: instance.id ), remote: true,form_class: "wake-up"

app/views/layouts/_header.html.haml
%div#header
  %nav.navbar.navbar-default
    %div.container-fluid
      %div.navbar-header
        %button.navbar-toggle.collapsed{type: "button", data: {toggle:"collapse", target: "#"}}
          %span.sr-only
            Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{ href: "#"}
          Sogno

      %div.collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li.dropdown
            %a.dropdown-toggle{ href: "#", role: "button", aria: {expanded: "false"} }
              Instance State
              %span.caret
            %ul.dropdown-menu.state-menu{role:"menu"}
              - Ec2::Instance.states.each do |state|
                %li{state: "#{state}"}
                  %a{href:"#"}= state.capitalize
        %p.navbar-text.navbar-right
          Hello #{current_user.username}!

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Sogno
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = javascript_include_tag "columnselector"
    = csrf_meta_tags
  %body

    = render "layouts/header" 
        
    %div#main
      = yield